### ISSUE TITLE
Add support for constraint programming

### ISSUE THREAD

**Issue by Shmew** [matthewcrews/flips#53]
I've used the [CP-SAT Solver](https://developers.google.com/optimization/cp/cp_solver) to optimize job scheduling (thousands of jobs that run daily) that takes into account specific dependencies, resources, and time constraints. It was a massive pain to understand how to use the `Google.OrTools.Sat` namespace as their documentation is quite sparse.

It would be nice to have it supported with this library. In particular it was a nightmare converting [this](https://developers.google.com/optimization/scheduling/job_shop) into something usable.

**Comment by matthewcrews** [comment]
@Shmew Could you provide me some example problems/formulations with solutions that I can use for a test bed? I am wanting to understand the problem space to make sure that we get the "ergonomics" of using the library correct.

I am thinking that this will likely involve some new types to ensure that people do not try to use an incorrect type of model/solver combination.

**Comment by Shmew** [comment]
Here's an example (that's probably poorly done) [gist](https://gist.github.com/Shmew/25e1172ee6d0ce0f97ba5762e5be2c0d). This was to find the optimal schedule given the constraints defined in the json file for the job shop problem. I don't have much in terms of recommendations, I pretty much fumbled through this until I got something that I believed to be working.

Honestly it was a pain to get this far, as their documentation in many parts was python only, and pretty sparse. I had to trawl through the repo issue/google group/source code to figure out how to do it all, especially in a non-imperative style.

**Comment by matthewcrews** [comment]
@Shmew  I've been reading up on this and it appears to be a different enough domain that I think I would rather create a different library for that domain. My goal with this library was to create something simple specifically for LP/MIP.

It's sounds like an interesting problem though! I am going to need to do some more reading up and look at some real world problems to get my head around it.

I am also actively trying to learn more about Category and Type Theory in order to come up with better abstractions. There are some features coming in F# 5.0 which will make all of this easier.

This library was a great learning experience though and lays a foundation for doing this work. I have learned a ton from this experience and making something equivalent for CP-SAT Solver will likely be much faster.

**Comment by NatElkins** [comment]
Just want to chime in, I also have this use case.  I'm probably going to take a crack at using the Google OR library directly for a problem that is very similar to this one: https://developers.google.com/optimization/scheduling/employee_scheduling

There's a good .NET example here: https://github.com/google/or-tools/blob/master/examples/dotnet/ShiftSchedulingSat.cs

**Comment by matthewcrews** [comment]
I will be addressing this request with the [Coffy Library](https://github.com/matthewcrews/coffy). I will be adding this discussion to that library.

COFFY: **C**onstraint **O**ptimization **F**or **F**sharp **Y**ay
